const HTTP_RESPONSES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  FORBIDDEN: 403,
  CONFLICT: 409,
};
const HTTP_MESSAGES = {
  INTERNAL_SERVER_ERROR: 'Internal Server Error. Please try again later.',
};
module.exports = { HTTP_RESPONSES, HTTP_MESSAGES };
